### ISSUE TITLE
Is the bot down?

### ISSUE THREAD

**Issue by advnpzn** [cibinjoseph/covid19indiatracker_bot#4]
Hey I have checked the bot in telegram, looks like its offline.
I just wanted to know whether the bot will be up in future .

**Comment by cibinjoseph** [comment]
Sorry about the late reply. I wasn't expecting posts in here since we ported the bot to be used by just the admins of a tracking website to compare against other Covid databases. It will be up for now. However, no guarantees about the future.

**Comment by advnpzn** [comment]
> Sorry about the late reply. I wasn't expecting posts in here since we ported the bot to be used by just the admins of a tracking website to compare against other Covid databases. It will be up for now. However, no guarantees about the future.

Bit late but thanks for taking your time to reply to such a silly question.
